version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  statsd:
    image: prom/statsd-exporter:v0.18.0
    entrypoint: /bin/statsd_exporter
    command:
      - "--statsd.mapping-config=/etc/statsd-exporter/conf.yaml"
    expose:
      - 9125
      - 9102
    ports:
      - 9125:9125
      - 9102:9102 # Visit http://localhost:9102/metrics to see metrics in Prometheus format
    networks:
      - ratelimit-network
    volumes:
      - ./examples/prom-statsd-exporter/conf.yaml:/etc/statsd-exporter/conf.yaml

  ratelimit:
    build:
      context: ratelimit
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - statsd
    networks:
      - ratelimit-network
    volumes:
      - ./examples/ratelimit/config:/data/ratelimit/config
    environment:
      - USE_STATSD=true
      - STATSD_HOST=statsd
      - STATSD_PORT=9125
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
      - CONFIG_GRPC_XDS_NODE_ID=test-node-id
      - CONFIG_GRPC_XDS_SERVER_URL=ratelimit-xds-config-server:18000

  envoy-proxy:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/proxy.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
      - "8888"
      - "8001"
    ports:
      - "8888:8888"
      - "8001:8001"
    depends_on:
      - backend

  backend:
    build: backend
    ports:
      - 9999:9999
    networks:
       - ratelimit-network

  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ratelimit-network
      
  grafana:
    image: grafana/grafana:6.1.6
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - ratelimit-network


networks:
  ratelimit-network:
