{
 "title": "Fake API",
 "description": "Fake API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_requests_total[$interval])"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\",job=\"node\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"node\"} - (node_memory_Cached_bytes{instance=\"localhost:9100\",job=\"node\"} + node_memory_Buffers_bytes{instance=\"localhost:9100\",job=\"node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\",job=\"node\"} + node_memory_Buffers_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"localhost:9100\",job=\"node\"} - node_memory_SwapFree_bytes{instance=\"localhost:9100\",job=\"node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=\"$job\"}[$interval])"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}