---
domain: rl
descriptors:
  - key: auth_token
    rate_limit:
      name: freeTier
      requests_per_unit: 10
      unit: hour
  - key: auth_token
    value: client1
    rate_limit:
      name: client1
      unit: hour
      requests_per_unit: 20
  - key: auth_token
    value: client2
    rate_limit:
      name: client2
      unit: hour
      requests_per_unit: 30
